#version 430 core

layout (local_size_x = 10, local_size_y = 10, local_size_z = 1) in;
layout(rgba32f, binding = 0) uniform image2D img_output;

void main() {
    vec4 value = vec4(0.0, 0.0, 0.0, 1.0);
    ivec2 texel_coord = ivec2(gl_GlobalInvocationID.xy);
    value.x = float(texel_coord.x) / (gl_NumWorkGroups.x * gl_WorkGroupSize.x);
    value.y = float(texel_coord.y) / (gl_NumWorkGroups.y * gl_WorkGroupSize.y);
    imageStore(img_output, texel_coord, value);
}
